services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: edge-serve-ab:local
    container_name: edge-serve-app
    ports:
      - "8080:8080"
    environment:
      # Override anything you want here:
      ADMIN_TOKEN: "dev-admin-token"
      RATE_LIMIT_RPS: "5"
      RATE_LIMIT_BURST: "10"
      AB_WEIGHT_A: "1.0"
      AB_WEIGHT_B: "0.0"
      CANARY_ENABLED: "false"
      SHADOW_ENABLED: "true"
      MAX_BODY_BYTES: "10485760"
      # MODEL_VA_PATH: "/app/models/va.onnx"
      # MODEL_VB_PATH: "/app/models/vb.onnx"
    volumes:
      - ./models:/app/models:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 2s
      retries: 6
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    container_name: edge-serve-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      # map the config file
      - ./local/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # map the rules file
      - ./prometheus/recording_rules.yml:/etc/prometheus/recording_rules.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: edge-serve-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    ports:
      - "3000:3000"
    volumes:
      - ./local/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  # Optional always-on k6 container for exec/debug (sleeps)
  k6:
    image: grafana/k6:0.48.0
    container_name: edge-serve-k6
    depends_on:
      - app
    profiles: ["load"]   # only starts when the "load" profile is enabled
    environment:
      - BASE_URL=http://app:8080
    volumes:
      - ./load/k6:/scripts:ro
    entrypoint: ["sleep", "infinity"]

  # Dedicated CLI-friendly k6 runner (no custom entrypoint)
  k6-cli:
    image: grafana/k6:0.48.0
    container_name: edge-serve-k6-cli
    depends_on:
      - app
    profiles: ["load"]
    environment:
      - BASE_URL=http://app:8080
    volumes:
      - ./load/k6:/scripts:ro
    working_dir: /scripts   # lets you run 'k6 run infer.js' if you want
