global:
  scrape_interval: 5s
  scrape_timeout: 4s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "edge-serve"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8080"]

rule_files:
  - /etc/prometheus/recording_rules.yml
